increment: 100
sleep: 0
count:
- name: Count Address
  text: SELECT count(*) > $1 as check, count(*)  as count FROM gisowner.coa_opendata_address_hold;
  values: [10000]
buffer:
- name: count
  text: SELECT *  FROM gisowner.coa_opendata_address_hold;
  values:
- name: Create View
  text: CREATE OR REPLACE VIEW gisowner.coa_address_buffers_view_hold AS SELECT st_transform(ST_Buffer(st_transform(shape, 2264),1320),4326)::geometry shape, 1320::numeric(10,4) as distance, objectid, civicaddress_id FROM gisowner.coa_opendata_address_hold UNION SELECT st_transform(ST_Buffer(st_transform(shape, 2264),660),4326)::geometry shape, 660::numeric(10,4) as distance, objectid, civicaddress_id FROM gisowner.coa_opendata_address_hold  UNION SELECT st_transform(ST_Buffer(st_transform(shape, 2264),330),4326)::geometry shape, 330::numeric(10,4) as distance, objectid, civicaddress_id FROM gisowner.coa_opendata_address_hold  UNION SELECT st_transform(ST_Buffer(st_transform(shape, 2264),165),4326)::geometry shape, 165::numeric(10,4) as distance, objectid, civicaddress_id FROM gisowner.coa_opendata_address_hold  UNION SELECT st_transform(ST_Buffer(st_transform(shape, 2264),82.5),4326)::geometry shape, 82.5::numeric(10,4) as distance, objectid, civicaddress_id FROM gisowner.coa_opendata_address_hold;
  values:
- name: truncate buffers
  text: TRUNCATE table gisowner.coa_address_buffers_cache_hold;
  values:
- name: create buffers
  text: INSERT INTO gisowner.coa_address_buffers_cache_hold (SELECT (row_number() OVER (ORDER BY (SHAPE)))::integer as objectid, distance, civicaddress_id, shape FROM gisowner.coa_address_buffers_view_hold ORDER BY distance DESC);
  values:
- name: vacuum buffers
  text: VACUUM ANALYZE gisowner.coa_address_buffers_cache_hold
  values:
- name: reindex buffers
  text: REINDEX TABLE gisowner.coa_address_buffers_cache_hold;
  values:
- name: clear cache
  text: TRUNCATE TABLE gisowner.coa_overlay_data_cache_hold;
  values:
- name: Resequence Cache HOLD
  text: ALTER SEQUENCE gisowner.coa_overlay_data_cache_hold_objectid_seq RESTART WITH 1;;
  values:
- name: ReIndex Buffer Shapes
  text: REINDEX INDEX gisowner.coa_address_buffers_cache_hold_shape;
  values:
- name: ReIndex Neighborhood Shapes
  text: REINDEX INDEX gisowner.coa_opendata_asheville_neighborhoods_hold_shape;
  values:
- name: ReIndex City Limits Shapes
  text: REINDEX INDEX gisowner.coa_opendata_city_limits_hold_shape;
  values:
- name: ReIndex Crime Shapes
  text: REINDEX INDEX gisowner.coa_opendata_crime_hold_shape;
  values:
- name: ReIndex Permit Shapes
  text: REINDEX INDEX gisowner.coa_opendata_permits_hold_shape;
  values:
- name: ReIndex Property Shapes
  text: REINDEX INDEX gisowner.coa_opendata_property_hold_shape;
  values:
- name: ReIndex Sanitation Shapes
  text: REINDEX INDEX gisowner.coa_opendata_sanitation_districts_hold_shape;
  values:
- name: ReIndex Sanitation Shapes
  text: REINDEX INDEX gisowner.coa_opendata_streets_hold_shape;
  values:
- name: ReIndex Zoning Shapes
  text: REINDEX INDEX gisowner.coa_opendata_zoning_hold_shape;
  values:
- name: ReIndex Zoning Overlays Shapes
  text: REINDEX INDEX gisowner.coa_opendata_zoning_overlays_hold_shape;
  values:
- name: vaucum cache
  text: VACUUM ANALYZE gisowner.coa_overlay_data_cache_hold;
  values:
buffercheck:
- name: check buffers
  text: SELECT( (SELECT COUNT(*) FROM gisowner.coa_address_buffers_cache_hold) = (SELECT COUNT(*) FROM gisowner.coa_opendata_address_hold)*$1) as check
  values: [5]
- name:  count distances
  text: SELECT DISTINCT COUNT(distance) OVER() = $1 as check FROM gisowner.coa_address_buffers_cache_hold GROUP BY distance HAVING COUNT(distance) > 0;
  values: [5]
buildcache:
- name: Crime
  text: INSERT INTO gisowner.coa_overlay_data_cache_hold (SELECT DISTINCT avw.civicaddress_id, 'CRIME'::varchar(150) as type, avw.distance as distance, (SELECT string_agg(tp,',')::text FROM (SELECT b.pid::text as tp FROM gisowner.coa_opendata_crime_hold b WHERE st_contains(avw.shape,b.shape )) as hold)::text as data,''::text datajson FROM gisowner.coa_address_buffers_cache_hold AS avw LEFT JOIN gisowner.coa_address_buffers_cache_hold buf ON buf.civicaddress_id = avw.civicaddress_id LEFT JOIN gisowner.coa_opendata_address_hold addr ON addr.civicaddress_id = buf.civicaddress_id WHERE avw.distance = ANY($3::numeric[]) and avw.civicaddress_id in (select civicaddress_id from gisowner.coa_opendata_address_hold order by civicaddress_id limit $1 offset $2))
  values: [82.5000,660.0000,1320.0000,330.0000,65.0000]
- name: Permits
  text: INSERT INTO gisowner.coa_overlay_data_cache_hold (SELECT DISTINCT avw.civicaddress_id,'PERMITS'::varchar(150) as type, avw.distance as distance, (SELECT string_agg(tp,',')::text FROM (SELECT DISTINCT b.apn::text as tp FROM gisowner.coa_opendata_permits_hold b WHERE st_contains(avw.shape,b.shape) ) as hold)::text as data, ''::text datajson FROM gisowner.coa_address_buffers_cache_hold AS avw LEFT JOIN gisowner.coa_address_buffers_cache_hold buf ON buf.civicaddress_id = avw.civicaddress_id LEFT JOIN gisowner.coa_opendata_address_hold addr ON addr.civicaddress_id = buf.civicaddress_id WHERE avw.distance = ANY($3::numeric[]) and avw.civicaddress_id in (select civicaddress_id from gisowner.coa_opendata_address_hold order by civicaddress_id limit $1 offset $2))
  values: [82.5000,660.0000,1320.0000,330.0000,65.0000]
- name: Address In City
  text: INSERT INTO gisowner.coa_overlay_data_cache_hold (SELECT DISTINCT civx.civicaddress_id, 'ADDRESS IN CITY'::varchar(150) as type,$3::numeric(38,8) as distance,CASE WHEN (SELECT string_agg(tp,',')::text FROM (SELECT b.jurisdiction_type::text as tp FROM gisowner.coa_opendata_city_limits_hold b WHERE st_intersects(addr.shape,b.shape))  as hold)::varchar(255) like '%Asheville Corporate Limits%' THEN 'YES' ELSE 'NO' END as data FROM gisowner.coa_opendata_property_hold as a LEFT JOIN gisowner.coa_civicaddress_pinnum_centerline_xref_view_hold civx ON civx.pinnum = a.pinnum LEFT JOIN gisowner.coa_opendata_address_hold addr ON addr.civicaddress_id = civx.civicaddress_id WHERE addr.civicaddress_id in (select distinct civicaddress_id from gisowner.coa_opendata_address_hold order by civicaddress_id limit $1 offset $2));
  values: [0]
- name: Zoning
  text: INSERT INTO gisowner.coa_overlay_data_cache_hold (SELECT DISTINCT civx.civicaddress_id,'ZONING'::varchar(150) as type,$3:: numeric(38,8) as distance, (SELECT string_agg(tp,',')::text FROM (SELECT b.districts::text as tp FROM gisowner.coa_opendata_zoning_hold b WHERE st_intersects(b.shape,a.shape) ) as hold)::text as data FROM gisowner.coa_opendata_property_hold as a  LEFT JOIN gisowner.coa_civicaddress_pinnum_centerline_xref_view_hold as civx ON civx.pinnum = a.pinnum LEFT JOIN gisowner.coa_opendata_address_hold as addr ON addr.civicaddress_id = civx.civicaddress_id WHERE addr.civicaddress_id in (select civicaddress_id from gisowner.coa_opendata_address_hold order by civicaddress_id  limit $1 offset $2 ));
  values: [0]
- name: Zoning Overlays
  text: INSERT INTO gisowner.coa_overlay_data_cache_hold (SELECT DISTINCT civx.civicaddress_id,'ZONING OVERLAYS'::varchar(150) as type,$3:: numeric(38,8) as distance, (SELECT string_agg(tp,',')::text FROM (SELECT (b.name || '-' || b.overlay_type)::text as tp FROM gisowner.coa_opendata_zoning_overlays_hold b WHERE st_intersects(b.shape,a.shape) ) as hold)::text as data FROM gisowner.coa_opendata_property_hold as a  LEFT JOIN gisowner.coa_civicaddress_pinnum_centerline_xref_view_hold as civx ON civx.pinnum = a.pinnum LEFT JOIN gisowner.coa_opendata_address_hold as addr ON addr.civicaddress_id = civx.civicaddress_id WHERE addr.civicaddress_id in (select civicaddress_id from gisowner.coa_opendata_address_hold order by civicaddress_id  limit $1 offset $2));
  values: [0]
- name: Trash Day
  text: INSERT INTO gisowner.coa_overlay_data_cache_hold (SELECT DISTINCT civx.civicaddress_id, 'TRASH DAY'::varchar(150) as type, $3:: numeric(38,8) as distance, (SELECT string_agg(tp,',')::text FROM (SELECT b.truckday::text as tp FROM gisowner.coa_opendata_sanitation_districts_hold b WHERE st_intersects(b.shape,addr.shape) ) as hold)::text as data FROM gisowner.coa_opendata_property_hold as a LEFT JOIN gisowner.coa_civicaddress_pinnum_centerline_xref_view_hold as civx ON civx.pinnum = a.pinnum LEFT JOIN gisowner.coa_opendata_address_hold as addr ON addr.civicaddress_id = civx.civicaddress_id WHERE addr.civicaddress_id in (SELECT civicaddress_id FROM gisowner.coa_opendata_address_hold ORDER BY civicaddress_id LIMIT $1 OFFSET $2));
  values: [0]
- name: Recycle Day
  text: INSERT INTO gisowner.coa_overlay_data_cache_hold (SELECT DISTINCT civx.civicaddress_id, 'RECYCLE DAY'::varchar(150) as type, $3:: numeric(38,8) as distance, (SELECT string_agg(tp,',')::text FROM (SELECT (b.recday || ' (Recycle Week ' || b.recdistrict || ')')::text as tp FROM gisowner.coa_opendata_sanitation_districts_hold b WHERE st_intersects(b.shape,addr.shape) ) as hold)::text as data FROM gisowner.coa_opendata_property_hold as a LEFT JOIN gisowner.coa_civicaddress_pinnum_centerline_xref_view_hold as civx ON civx.pinnum = a.pinnum LEFT JOIN gisowner.coa_opendata_address_hold as addr ON addr.civicaddress_id = civx.civicaddress_id WHERE addr.civicaddress_id in (SELECT civicaddress_id FROM gisowner.coa_opendata_address_hold ORDER BY civicaddress_id LIMIT $1 OFFSET $2));
  values: [0]
- name: Remove Blanks
  text: DELETE FROM gisowner.coa_overlay_data_cache_hold WHERE data is null and ($3=$3 or $2=$2 or $1=$1)
  values: [0]
