testname: crime
onsuccess:
- name: truncate crimes
  text: TRUNCATE TABLE gisowner.coa_opendata_crime;
  values:
- name: insert crimes
  text: INSERT INTO gisowner.coa_opendata_crime (SELECT * FROM gisowner.coa_opendata_crime_hold);
  values:
tests:
- name: count crimes
  text: SELECT count(*) > $1 as check FROM gisowner.coa_opendata_crime;
  values: [10000]
- name: count neighborhood in crime
  text: SELECT count(*) > $1 as check FROM gisowner.coa_opendata_crime WHERE neighborhood is not null;
  values: [-2]
- name: Duplicate PIDS
  text: SELECT COALESCE( (SELECT count(pid)  as check from gisowner.coa_opendata_crime_hold group by pid having count(pid) > 1),0) = $1 as check;
  values: [0]
- name: offense types
  text: SELECT DISTINCT COUNT(offense) OVER() > $1 as check FROM gisowner.coa_opendata_address_hold GROUP BY offense HAVING COUNT(offense) > 0 ;
  values: [5]
