testname: Permits
onsuccess:
- name: truncate Permits
  text: TRUNCATE TABLE gisowner.coa_opendata_permits;
  values:
- name: insert crimes
  text: INSERT INTO gisowner.coa_opendata_permits (SELECT * FROM gisowner.coa_opendata_permits_hold);
  values:
tests:
- name: count permits
  text: SELECT count(*) > $1 as check FROM gisowner.coa_opendata_permits_hold;
  values: [100000]
- name: APN count
  text: SELECT DISTINCT COUNT(apn) OVER() > $1 as check FROM gisowner.coa_opendata_permits_hold GROUP BY apn HAVING COUNT(apn) > 0 ;
  values: [1000]
- name: count neighborhood in permits
  text: SELECT count(*) > $1 as check FROM gisowner.coa_opendata_permits_hold WHERE neighborhood is not null;
  values: [100]
- name: count comments in permits
  text: SELECT count(*) > $1 as check FROM gisowner.coa_opendata_permits_hold WHERE record_comments is not null;
  values: [1000]
- name: record_module count
  text: SELECT DISTINCT COUNT(record_module) OVER() > $1 as check FROM gisowner.coa_opendata_permits_hold GROUP BY record_module HAVING COUNT(record_module) > 0 ;
  values: [2]
- name: record_type count
  text: SELECT DISTINCT COUNT(record_type) OVER() > $1 as check FROM gisowner.coa_opendata_permits_hold GROUP BY record_type HAVING COUNT(record_type) > 0 ;
  values: [5]
- name: record_type_type count
  text: SELECT DISTINCT COUNT(record_type_type) OVER() > $1 as check FROM gisowner.coa_opendata_permits_hold GROUP BY record_type_type HAVING COUNT(record_type_type) > 0 ;
  values: [5]
- name:  permits in last week
  text: SELECT COALESCE( ( SELECT count(*) FROM gisowner.coa_opendata_permits_hold WHERE  EXTRACT(WEEK FROM date_opened) = EXTRACT(WEEK FROM now()) and EXTRACT(YEAR FROM date_opened) = EXTRACT(YEAR FROM now())),0) > $1 as check;
  values: [0]
- name:  permits have multiple years
  text: SELECT DISTINCT COUNT(EXTRACT(YEAR FROM date_opened)) OVER() > $1 as check FROM gisowner.coa_opendata_permits_hold GROUP BY EXTRACT(YEAR FROM date_opened) HAVING COUNT(EXTRACT(YEAR FROM date_opened)) > 0 ;
  values: [3]
