testname: City Limits
onsuccess:
- name: truncate city limits
  text: TRUNCATE TABLE gisowner.coa_opendata_city_limits;
  values:
- name: insert City Limits
  text: INSERT INTO gisowner.coa_opendata_city_limits (SELECT * FROM gisowner.coa_opendata_city_limits_hold);
  values:
tests:
- name: count city limits
  text: SELECT count(*) > $1 as check FROM gisowner.coa_opendata_city_limits_hold;
  values: [2]
- name: count city name
  text: SELECT DISTINCT COUNT(jurisdiction_type) OVER() >= $1 as check FROM gisowner.coa_opendata_city_limits_hold GROUP BY jurisdiction_type HAVING COUNT(jurisdiction_type) > 0 ;
  values: [1]
