testname: Zoning
onsuccess:
- name: truncate Zoning
  text: TRUNCATE TABLE gisowner.coa_opendata_zoning;
  values:
- name: insert Zoning
  text: INSERT INTO gisowner.coa_opendata_zoning (SELECT * FROM gisowner.coa_opendata_zoning_hold);
  values:
tests:
- name: count Zoning
  text: SELECT count(*) > $1 as check FROM gisowner.coa_opendata_zoning_hold;
  values: [100]
- name: count districts in Zoning
  text: SELECT DISTINCT COUNT(districts) OVER() > $1 as check FROM gisowner.coa_opendata_zoning_hold GROUP BY districts HAVING COUNT(districts) > 0;
  values: [10]
- name: location districts
  text: SELECT DISTINCT COUNT(districts) OVER() > $1 as check FROM gisowner.coa_opendata_zoning_hold GROUP BY districts HAVING COUNT(districts) > 0 ;
  values: [10]
